In [ ]:
%load_ext autoreload
%autoreload 2
%load_ext line_profiler

In [ ]:
import pandas as pd 
from travis_attack.utils import display_all

In [ ]:
filename_results = f"/data/tproth/travis_attack/baselines/results.csv"
df_results = pd.read_csv(filename_results)
df_results[['date', 'time']] = df_results['datetime'].str.split('_', 1, expand=True)
first_cols = ['datetime','date','time']
last_cols = [col for col in df_results.columns if col not in first_cols]
df_results = df_results[first_cols+last_cols]
df_results = df_results.query("date > '2022-04-22'")
df_results = df_results.sort_values(by=['ds_name', "attack_num"])
display_all(df_results[["ds_name"]])

,datetime,date,time,ds_name,split,sts_threshold,contradiction_threshold,acceptability_threshold,pp_letter_diff_threshold,attack_num,attack_code,successful_attacks,failed_attacks,skipped_attacks,original_accuracy,attack_accuracy_perc,attack_success_rate,avg_word_perturbed,avg_word_perturbed_perc,max_words_changed,avg_num_queries,avg_original_perplexity,avg_attack_perplexity,avg_attack_use_score
1,2022-07-04_154734,2022-07-04,154734,financial,test,0.8,0.2,0.5,30,1,LM-WR-BS-b2m5,62,97,0,100.0,61.01,38.99,12.95,13.57,5,58.23,86.39,95.36,0.83
2,2022-07-04_160601,2022-07-04,160601,financial,test,0.8,0.2,0.5,30,2,LM-WR-BS-b5m25,110,49,0,100.0,30.82,69.18,12.95,12.13,6,290.12,74.75,94.17,0.84
4,2022-07-04_170544,2022-07-04,170544,financial,test,0.8,0.2,0.5,30,3,LM-WR-BS-b10m50,120,39,0,100.0,24.53,75.47,12.95,12.04,6,697.15,76.03,100.79,0.84
6,2022-07-04_192519,2022-07-04,192519,financial,test,0.8,0.2,0.5,30,4,LM-WADR-BS-b5m25,145,14,0,100.0,8.81,91.19,12.95,44.59,17,1330.79,69.43,103.21,0.85
7,2022-07-04_230534,2022-07-04,230534,financial,test,0.8,0.2,0.5,30,5,CF-WR-BS-b5m25,103,56,0,100.0,35.22,64.78,12.95,15.14,6,498.25,73.15,158.47,0.84
9,2022-07-05_003315,2022-07-05,003315,financial,test,0.8,0.2,0.5,30,6,LM-WR-GA-m25p60mi20mr5,110,49,0,100.0,30.82,69.18,12.95,13.96,8,463.45,73.96,102.58,0.83
0,2022-07-04_154021,2022-07-04,154021,rotten_tomatoes,test,0.8,0.2,0.5,30,1,LM-WR-BS-b2m5,142,217,0,100.0,60.45,39.55,10.69,16.76,6,41.84,70.87,84.10,0.83
3,2022-07-04_160243,2022-07-04,160243,rotten_tomatoes,test,0.8,0.2,0.5,30,2,LM-WR-BS-b5m25,249,110,0,100.0,30.64,69.36,10.69,16.87,6,281.51,69.22,100.31,0.82
5,2022-07-04_173617,2022-07-04,173617,rotten_tomatoes,test,0.8,0.2,0.5,30,3,LM-WR-BS-b10m50,277,82,0,100.0,22.84,77.16,10.69,16.25,6,790.34,68.82,99.77,0.82
8,2022-07-04_213810,2022-07-04,213810,rotten_tomatoes,test,0.8,0.2,0.5,30,4,LM-WADR-BS-b5m25,337,22,0,100.0,6.13,93.87,10.69,48.89,16,976.41,68.46,109.33,0.85
10,2022-07-05_022203,2022-07-05,022203,rotten_tomatoes,test,0.8,0.2,0.5,30,5,CF-WR-BS-b5m25,285,74,0,100.0,20.61,79.39,10.69,18.65,6,326.60,67.96,138.02,0.83
11,2022-07-05_040131,2022-07-05,040131,rotten_tomatoes,test,0.8,0.2,0.5,30,6,LM-WR-GA-m25p60mi20mr5,248,111,0,100.0,30.92,69.08,10.69,19.61,8,424.92,68.54,101.57,0.81

In [ ]:
df_results[["datetime", "ds_name", "attack_num", "attack_code", "successful_attacks", "attack_success_rate", "avg_num_queries"]].sort_values(["attack_num", "ds_name"], ascending=[True,False])

,datetime,ds_name,attack_num,attack_code,successful_attacks,attack_success_rate,avg_num_queries
0,2022-07-04_154021,rotten_tomatoes,1,LM-WR-BS-b2m5,142,39.55,41.84
1,2022-07-04_154734,financial,1,LM-WR-BS-b2m5,62,38.99,58.23
3,2022-07-04_160243,rotten_tomatoes,2,LM-WR-BS-b5m25,249,69.36,281.51
2,2022-07-04_160601,financial,2,LM-WR-BS-b5m25,110,69.18,290.12
5,2022-07-04_173617,rotten_tomatoes,3,LM-WR-BS-b10m50,277,77.16,790.34
4,2022-07-04_170544,financial,3,LM-WR-BS-b10m50,120,75.47,697.15
8,2022-07-04_213810,rotten_tomatoes,4,LM-WADR-BS-b5m25,337,93.87,976.41
6,2022-07-04_192519,financial,4,LM-WADR-BS-b5m25,145,91.19,1330.79
10,2022-07-05_022203,rotten_tomatoes,5,CF-WR-BS-b5m25,285,79.39,326.60
7,2022-07-04_230534,financial,5,CF-WR-BS-b5m25,103,64.78,498.25
11,2022-07-05_040131,rotten_tomatoes,6,LM-WR-GA-m25p60mi20mr5,248,69.08,424.92
9,2022-07-05_003315,financial,6,LM-WR-GA-m25p60mi20mr5,110,69.18,463.45

In [ ]:
filename_run = "/data/tproth/travis_attack/baselines/2022-04-28_232643_rotten_tomatoes_valid_BeamSearchCFEmbeddingAttack_beam_sz=5_max_candidates=25_processed.csv"
df = pd.read_csv(filename_run)

In [ ]:
display_all(df.sample(2))

,ground_truth_output,num_queries,original_output,original_score,original_text,perturbed_output,perturbed_score,perturbed_text,result_type,truelabel,orig_predclass,pp_predclass,orig_truelabel_probs,pp_truelabel_probs,vm_scores,label_flip,sts_scores,contradiction_scores,sts_threshold_met,contradiction_threshold_met
550,0.0,266.0,0.0,0.245339,"amid the shock and curiosity factors , the film is just a corny examination of a young actress trying to find her way .",1.0,0.589488,"amid the shock and curiosity factors , the film is just a hokey examination of a young actress trying to find her way .",Successful,0,0,1,0.75466,0.410513,0.344147,1,0.977341,0.000486,True,True
387,1.0,219.0,1.0,0.480720,"although tender and touching , the movie would have benefited from a little more dramatic tension and some more editing .",0.0,0.819396,"although tender and touching , the movie would have been from a little more dramatic tension and some more editing .",Successful,1,1,0,0.51928,0.180605,0.338675,1,0.972206,0.001476,True,True

In [ ]:
good_example_idxs = [360, 714, 247]
bad_example_idxs = [690,323,308]

display_all(df.iloc[bad_example_idxs])

,ground_truth_output,num_queries,original_output,original_score,original_text,perturbed_output,perturbed_score,perturbed_text,result_type,truelabel,orig_predclass,pp_predclass,orig_truelabel_probs,pp_truelabel_probs,vm_scores,label_flip,sts_scores,contradiction_scores,sts_threshold_met,contradiction_threshold_met
690,0.0,2068.0,0.0,0.062339,"this little film is so slovenly done , so primitive in technique , that it can't really be called animation .",1.0,0.664022,"this little film is so slovenly accomplished , so elemental in technique , that it can't really be called abetted .",Successful,0,0,1,0.937661,0.335977,0.601683,1,0.859913,0.363196,True,True
323,1.0,151.0,1.0,0.212919,"may be more genial than ingenious , but it gets the job done .",0.0,0.896022,"may be more genial than ingenious , but it gets the job ended .",Successful,1,1,0,0.787081,0.103978,0.683103,1,0.786201,0.643740,True,True
308,1.0,907.0,1.0,0.042907,". . . bright , intelligent , and humanly funny film .",0.0,0.905542,". . . radioactive , canny , and humanly joke film .",Successful,1,1,0,0.957093,0.094458,0.862635,1,0.719449,0.015210,True,True